### ISSUE TITLE
The program encountered an error when running to the “Start Combining” step.

### ISSUE THREAD

**Issue by biginfor** [ZijieJin/scFusion#4]
Dear developers：
          Thank you for showing us such a software that can predict gene fusion through single cell sequencing data.I encountered such a problem when running the program.But I can't solve it.I hope you can help.（p.s.All parameters are default values）

python scfusion/scFusion-1.3/scFusion.py -f scfusion/scFusion-1.3/Testdata/  -b 1 -e 10 -s /scfusion/STAR/genomeindice -t 8 -n 0.9 -g scfusion/fastq/hg19 -a scfusion/refgenegtf/hg19.refGene.gtf

results:
...
...
Finish Basic Processing! Index: 5 ~ 6
Finish Basic Processing! Index: 9 ~ 10
Finish Basic Processing! Index: 1 ~ 2
Finish Basic Processing! Index: 7 ~ 8

Start Combining!

Traceback (most recent call last):
  File "path to main.py file/scFusion.py", line 266, in <module>
    aaa = subprocess.check_output(
  File "anaconda/envs/r410/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "anaconda/envs/r410/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sh /scfusion/scFusion-1.3/bin/CombinePipeline_startwith_FS.sh /scfusion/scFusion-1.3/Testdata// 1 10 . /scfusion/scFusion-1.3/bin/../data/weight-V9-2.hdf5 /scfusion/fastq/hg19 /scfusion/refgenegtf/hg19.refGene.gtf.added /scfusion/scFusion-1.3/bin/' returned non-zero exit status 1.
I sincerely hope you can reply to me！

**Comment by ZijieJin** [comment]
Can you run command "sh /scfusion/scFusion-1.3/bin/CombinePipeline_startwith_FS.sh /scfusion/scFusion-1.3/Testdata// 1 10 . /scfusion/scFusion-1.3/bin/../data/weight-V9-2.hdf5 /scfusion/fastq/hg19 /scfusion/refgenegtf/hg19.refGene.gtf.added /scfusion/scFusion-1.3/bin" and post the error message here?

It seems the path of your STAR index file is not correct, I guess you should delete the / at the beginning?

**Comment by ZijieJin** [comment]
It seems the path of your STAR index file is not correct, I guess you should delete the / at the beginning?

**Comment by ZijieJin** [comment]
@biginfor If the command it right, could you please show the format of your gtf here? Different gtf files may be in different format.

**Comment by biginfor** [comment]
sorry , the full path of my  STAR index file is  /xtdisk/_group/_myname/cancer/scfusion/STAR/genomeindice

**Comment by ZijieJin** [comment]
Try the correct path. If this error still exists, please show me the gtf file. I guess the gtf file caused this problem

**Comment by biginfor** [comment]
I think my path is correct，These are the first few lines of my GTF file.Sorry, I haven't learned how to add pictures yet.
chr1	refGene	transcript	11869	14362	.	+	.	gene_id "LOC102725121"; transcript_id "NR_148357";  gene_name "LOC102725121";
chr1	refGene	exon	11869	12227	.	+	.	gene_id "LOC102725121"; transcript_id "NR_148357"; exon_number "1"; exon_id "NR_148357.1"; gene_name "LOC102725121";
chr1	refGene	exon	12613	12721	.	+	.	gene_id "LOC102725121"; transcript_id "NR_148357"; exon_number "2"; exon_id "NR_148357.2"; gene_name "LOC102725121";
chr1	refGene	exon	13221	14362	.	+	.	gene_id "LOC102725121"; transcript_id "NR_148357"; exon_number "3"; exon_id "NR_148357.3"; gene_name "LOC102725121";
chr1	refGene	transcript	11874	14409	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018";  gene_name "DDX11L1";
chr1	refGene	exon	11874	12227	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018"; exon_number "1"; exon_id "NR_046018.1"; gene_name "DDX11L1";
chr1	refGene	exon	12613	12721	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018"; exon_number "2"; exon_id "NR_046018.2"; gene_name "DDX11L1";
chr1	refGene	exon	13221	14409	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018"; exon_number "3"; exon_id "NR_046018.3"; gene_name "DDX11L1";
chr22	refGene	transcript	24666799	24813706	.	+	.	gene_id "SPECC1L"; transcript_id "NM_015330";  gene_name "SPECC1L";
chr22	refGene	exon	24666799	24666951	.	+	.	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "1"; exon_id "NM_015330.1"; gene_name "SPECC1L";
chr22	refGene	5UTR	24666799	24666951	.	+	.	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "1"; exon_id "NM_015330.1"; gene_name "SPECC1L";
chr22	refGene	exon	24672668	24672771	.	+	.	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "2"; exon_id "NM_015330.2"; gene_name "SPECC1L";
chr22	refGene	5UTR	24672668	24672771	.	+	.	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "2"; exon_id "NM_015330.2"; gene_name "SPECC1L";
chr22	refGene	exon	24698163	24698352	.	+	.	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "3"; exon_id "NM_015330.3"; gene_name "SPECC1L";
chr22	refGene	5UTR	24698163	24698199	.	+	.	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "3"; exon_id "NM_015330.3"; gene_name "SPECC1L";
chr22	refGene	CDS	24698200	24698352	.	+	0	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "3"; exon_id "NM_015330.3"; gene_name "SPECC1L";
chr22	refGene	exon	24709281	24709434	.	+	.	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "4"; exon_id "NM_015330.4"; gene_name "SPECC1L";
chr22	refGene	CDS	24709281	24709434	.	+	0	gene_id "SPECC1L"; transcript_id "NM_015330"; exon_number "4"; exon_id "NM_015330.4"; gene_name "SPECC1L";

**Comment by ZijieJin** [comment]
Can you run command "sh scfusion/scFusion-1.3/bin/CombinePipeline_startwith_FS.sh scfusion/scFusion-1.3/Testdata// 1 10 . scfusion/scFusion-1.3/bin/../data/weight-V9-2.hdf5 scfusion/fastq/hg19 scfusion/refgenegtf/hg19.refGene.gtf.added scfusion/scFusion-1.3/bin" and post the error message here? (Set the correct path.) No problem with the gif file

**Comment by biginfor** [comment]
**Most of the output is like this：**
IR5692A1!!!STX5	MIR5692A1!!!SDHA	CNBD1!!!SDHA	MIR5692A2!!!SENP6	PGM5P3-AS1!!!SENP6	SLC1A4!!!SENP6	SNORA105A!!!SENP6	SNORA105B!!!PFDN5	MIR1268A!!!PGM5P3-AS1	IKZF1!!!PGM5P3-AS1	MIR5692A1!!!SNORA105A	IKZF1!!!SNORA105A	MIR5692A1!!!SNORA105B	IKZF1!!!SNORA105B	MIR5692A1!!!MALAT1	MALAT1!!!MALAT1	MIR1234!!!MALAT1	MIR3654!!!MALAT1	TALAM1!!!MIR1234	MIR1234!!!MIR1234	MIR3654!!!MIR1234	TALAM1!!!MIR3654	TALAM1!!!PGM5P3-AS1	FAM72C!!!PGM5P3-AS1	H3P6!!!PGM5P3-AS1	MIR548F3!!!PGM5P3-AS1	SRGAP2D!!!SNORA105A	FAM72C!!!SNORA105A  H3P6!!!SNORA105A	MIR548F3!!!SNORA105A	SRGAP2D!!!SNORA105B	FAM72C!!!SNORA105B	H3P6!!!SNORA105B	MIR548F3!!!SNORA105B	SRGAP2D!!!MALAT1    MIR1268A!!!MIR1234	MIR1268A!!!MIR3654
**until**
 “MIR1268ATraceback (most recent call last):”
File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//FindHomoPattern_RAM.py", line 282, in <module>
    reference = open(reffilepath)
IsADirectoryError: [Errno 21] Is a directory: '/xtdisk/fangxd_group/fangzhj/ACC/scfusion/fastq/hg19'
Starting: 1	Candidate Size: 0	Found Size: 0
Traceback (most recent call last):
  File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//FindChiDist.py", line 419, in <module>
    thischr2 = chr2num(CandidateList[l][3])
  File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//FindChiDist.py", line 24, in chr2num
    return int(str)
ValueError: invalid literal for int() with base 10: 'Un_gl000220'
Traceback (most recent call last):
  File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//PreProcessing_SingleFile.py", line 1, in <module>
    from keras.models import Sequential
  File "/home/fangzhj/.local/lib/python3.8/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/fangzhj/.local/lib/python3.8/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/home/fangzhj/.local/lib/python3.8/site-packages/keras/backend.py", line 36, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/software/biosoft/software/python/python2020/lib/python3.8/site-packages/tensorflow/python/eager/context.py)

**Comment by ZijieJin** [comment]
The first error message says that hg19 is a directory. Check it


On Sep 8, 2021, at 23:59, biginfor ***@***.***> wrote:

﻿

Most of the output is like this：
IR5692A1!!!STX5 MIR5692A1!!!SDHA CNBD1!!!SDHA MIR5692A2!!!SENP6 PGM5P3-AS1!!!SENP6 SLC1A4!!!SENP6 SNORA105A!!!SENP6 SNORA105B!!!PFDN5 MIR1268A!!!PGM5P3-AS1 IKZF1!!!PGM5P3-AS1 MIR5692A1!!!SNORA105A IKZF1!!!SNORA105A MIR5692A1!!!SNORA105B IKZF1!!!SNORA105B MIR5692A1!!!MALAT1 MALAT1!!!MALAT1 MIR1234!!!MALAT1 MIR3654!!!MALAT1 TALAM1!!!MIR1234 MIR1234!!!MIR1234 MIR3654!!!MIR1234 TALAM1!!!MIR3654 TALAM1!!!PGM5P3-AS1 FAM72C!!!PGM5P3-AS1 H3P6!!!PGM5P3-AS1 MIR548F3!!!PGM5P3-AS1 SRGAP2D!!!SNORA105A FAM72C!!!SNORA105A H3P6!!!SNORA105A MIR548F3!!!SNORA105A SRGAP2D!!!SNORA105B FAM72C!!!SNORA105B H3P6!!!SNORA105B MIR548F3!!!SNORA105B SRGAP2D!!!MALAT1 MIR1268A!!!MIR1234 MIR1268A!!!MIR3654
until
“MIR1268ATraceback (most recent call last):”
File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//FindHomoPattern_RAM.py", line 282, in
reference = open(reffilepath)
IsADirectoryError: [Errno 21] Is a directory: '/xtdisk/fangxd_group/fangzhj/ACC/scfusion/fastq/hg19'
Starting: 1 Candidate Size: 0 Found Size: 0
Traceback (most recent call last):
File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//FindChiDist.py", line 419, in
thischr2 = chr2num(CandidateList[l][3])
File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//FindChiDist.py", line 24, in chr2num
return int(str)
ValueError: invalid literal for int() with base 10: 'Un_gl000220'
Traceback (most recent call last):
File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//PreProcessing_SingleFile.py", line 1, in
from keras.models import Sequential
File "/home/fangzhj/.local/lib/python3.8/site-packages/keras/init.py", line 25, in
from keras import models
File "/home/fangzhj/.local/lib/python3.8/site-packages/keras/models.py", line 19, in
from keras import backend
File "/home/fangzhj/.local/lib/python3.8/site-packages/keras/backend.py", line 36, in
from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/software/biosoft/software/python/python2020/lib/python3.8/site-packages/tensorflow/python/eager/context.py)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZijieJin%2FscFusion%2Fissues%2F4%23issuecomment-915365262&data=04%7C01%7C%7C14464743a1ae41af895708d972e1a2b4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637667135687878208%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TDWKY5LlYjOl%2FWoXdWFfijdLuAeXic58BL%2Br5GVQTVQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNH4NCYNHF4IXQU5ME5NDDUA6B55ANCNFSM5DVB63PA&data=04%7C01%7C%7C14464743a1ae41af895708d972e1a2b4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637667135687888162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WyeZacJLw4QbfBOteXZWjHNxll4d%2B296fh41zm59rnc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C14464743a1ae41af895708d972e1a2b4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637667135687888162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IUZKueaQ34R8%2FLbpDs9Jl2rd9W0Lv010fYVVNZsd2tA%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C14464743a1ae41af895708d972e1a2b4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637667135687898121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZlVhbj92OSolhcVuz2RRRuLcHDHx%2BWDE7cXbYQtZdas%3D&reserved=0>.

**Comment by biginfor** [comment]
Dear developer:
       I updated my command line，just like this :
python /xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/scFusion.py -f /xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/Testdata/  -b 1 -e 10 -s /xtdisk/fangxd_group/fangzhj/ACC/scfusion/STAR/genomeindice -t 20 -n 0.9 -g /xtdisk/fangxd_group/fangzhj/ACC/scfusion/fastq/hg19/hg19.fa -a /xtdisk/fangxd_group/fangzhj/ACC/scfusion/refgenegtf/hg19.refGene.gtf -m /xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/data/hg19mappability75.txt -w /xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/data/weight-V9-2.hdf5
     Now I have received such a mistake：

**Traceback (most recent call last):
  File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//FindChiDist.py", line 419, in <module>
    thischr2 = chr2num(CandidateList[l][3])
  File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//FindChiDist.py", line 24, in chr2num
    return int(str)
ValueError: invalid literal for int() with base 10: 'Un_gl000220'**
2021-09-09 10:58:47.833374: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-09 10:58:47.833428: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by ZijieJin** [comment]
Got it. I will fix this bug later. If you want to run scFusion now, you can delete the line in your gtf file with chromosome other than chr1-22, X and Y.

**Comment by biginfor** [comment]
After solving the GTF file errors and all module import errors, I still encounter the following errors:
_Traceback (most recent call last):
  File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/scFusion.py", line 277, in <module>
    aaa = subprocess.check_output(
  File "/xtdisk/fangxd_group/fangzhj/anaconda/envs/r410/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/xtdisk/fangxd_group/fangzhj/anaconda/envs/r410/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sh /xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin/CombinePipeline_Retrain.sh /xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/Testdata// . /xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/data/weight-V9-2.hdf5 10 /xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin/' returned non-zero exit status 1._
and I run the  command mentioned above,it shows:

**2021-09-09 16:15:00.127952: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-09 16:15:00.128000: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//Data_preprocess_MyRetrain.py", line 28, in <module>
    read_new = read[0:MergePoint]+'H'+read[MergePoint:]
NameError: name 'MergePoint' is not defined
2021-09-09 16:15:11.893949: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-09 16:15:11.893992: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/bin//Model1_Retrain.py", line 69, in <module>
    Good_for_Tra = np.load(npydir + '/Good_for_Tra.npy')
  File "/xtdisk/fangxd_group/fangzhj/anaconda/envs/r410/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/xtdisk/fangxd_group/fangzhj/ACC/scfusion/scFusion-1.3/Testdata///Retrain//Good_for_Tra.npy'**

**Comment by ZijieJin** [comment]
you need to have libcudart.so.11.0 on your computer

On Sep 9, 2021, at 16:16, biginfor ***@***.******@***.***>> wrote:

'libcudart.so.11.0

**Comment by biginfor** [comment]
Dear Developer：
        Does this machine learning algorithm have to call GPU? 
        I think the most critical problem in the current error situation comes from the file Data_preprocessing_MyRetrain.py. The error statement shows: **_The variable "MergePoint" is not defined._** In fact, when I assigned a value of 0 to'MergePoint' and forced the tool to execute the step of MergePoint = int(readinfo_split[1]), the error status displayed **_out of list index,_** which indicated that there was a problem with the file reading, which led to **_'MergePoint'_** unable to extract the required string. I wonder how to solve this problem?Moreover,in the file **"Data_preprocessing_MyRetrain.py** , you use the code to import sys then call "ChimericFile = sys.argv[1]",could you tell me which file was read in this step?
       By the way , could you please provide the GTF file  you used? Thanks a lot.
       Happy Teachers's Day!

**Comment by ZijieJin** [comment]
Can you send me an email with your phone number or WeChat ID so that I can call you. Email: jzj2035198@outlook.com

**Comment by ZijieJin** [comment]
See #5. Can this discussion help you?

**Comment by ZijieJin** [comment]
Please see this discussion. #5

**Comment by ZijieJin** [comment]
Hi, you can send me Wechat message to talk about it
